[profile.default]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc = "0.8.25"
optimizer = true
optimizer_runs = 100000

bytecode_hash = "none"
cbor_metadata = false

# pre push0 for maximum compatibility
evm_version = "paris"

remappings = [
    "ethgild/=lib/ethgild/src/",
    "rain.factory/=lib/ethgild/lib/rain.factory/src/",
    "rain.flare/=lib/ethgild/lib/rain.flare/src/",
    "rain.extrospection/=lib/rain.extrospection/src/",
    "rain.pyth/=lib/ethgild/lib/rain.pyth/src/",
    "rain.intorastring/=lib/ethgild/lib/rain.pyth/lib/rain.interpreter/lib/rain.interpreter.interface/lib/rain.intorastring/src/",
    "rain.math.float/=lib/ethgild/lib/rain.pyth/lib/rain.interpreter/lib/rain.interpreter.interface/lib/rain.math.float/src/",
]